13 sprint
TY95MC/java-shareit pull request #1
Opened 2023-10-24 20:35 UTC by TY95MC

2023-10-24 21:55 UTC, AnastasiyaFomkina requested changes

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> + * TODO Sprint add-bookings.
В коммерческой разработке, когда код из `TODO` реализован, принято его удалять, чтобы он не путал других разработчиков.
Удали, пожалуйста, все `TODO`, которые были выполнены во всем проекте

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto add(@RequestHeader("X-Sharer-User-Id") Long userId,
Данный хэдер нам понадобиться и в других классах: нужно вынести его в отдельный класс и сделать его публичной константой, чтобы избежать дублирований. Чтобы быстро поправить все значения, можно воспользоваться горячими клавишами в IDEA: [Ctrl+Shift+R](https://www.jetbrains.com/help/idea/finding-and-replacing-text-in-project.html?keymap=primary_windows#replace_search_string_in_project)

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemService.java
Интерфейс и реализацию сервиса можно вынести в отдельный пакет, например, `service`

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (dto.getName() == null || dto.getDescription() == null || dto.getAvailable() == null ||
Нужно добавить аннотации валидации для полей, а не проверять их вручную

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/model/ItemMapper.java
> +public class ItemMapper {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemDtoMapper.java
Объедини, пожалуйста, два класса мапперов в один класс, так сильно дробить мапперы не нужно

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepositoryImpl.java
> +        if (tmp.isPresent()) {
Удобнее использовать [orElseThrow()](https://www.geeksforgeeks.org/optional-orelsethrow-method-in-java-with-examples/). Так метод получиться сократить до одной строки

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDtoMapper.java
> +public class ItemRequestDtoMapper {
Объедини, пожалуйста, два маппера в один - для ItemRequest и ItemRequestDto

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/dto/UserDtoMapper.java
> +public class UserDtoMapper {
Объедини, пожалуйста, мапперы для пользователя в один класс

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        if (dto.getEmail() == null || dto.getName() == null) {
Используй `@NotNull` и `@NotBlank`. Вот [отличная статья](https://reflectoring.io/bean-validation-with-spring-boot/) про спринговую валидацию

2023-10-24 21:55 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        if (userIdToUser.values().stream().anyMatch(user -> user.getEmail().equals(email) && !user.getId().equals(userId))) {
_Дополнительные оптимизации_
Чтобы проверка почты проходила за [O(1)](https://skillbox.ru/media/code/big-o-notation-chto-eto-takoe-i-kak-eye-poschitat/), нужно завести Set, куда при добавлении нового пользователя мы будем класть его email. Соответственно, перед тем как добавить пользователя, нужно будет посмотреть, есть ли уже в сете подобный email, если есть - то пользователь с таким email уже существует.

Так как поиск и вставка в сете работают в среднем за O(1), то наш алгоритм поиска одинаковых email тоже будет работать в среднем за O(1), а это гораздо быстрее, чем пройтись по всем элементам списка O(n)

2023-10-25 07:30 UTC, TY95MC commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        if (userIdToUser.values().stream().anyMatch(user -> user.getEmail().equals(email) && !user.getId().equals(userId))) {
Дело в том, что, согласно тестам Постмана, пользователь может выполнить обновление своего email на такой же,  т.е. был user@user.com и обновить его можно на абсолютно идентичный user@user.com. Таким образом проверку все равно необходимо выполнять на занятость другими пользователями(нам нужно знать и айдишник других пользователей). 
Предложенное вами решение отлично подходит для добавления новых пользователей. Для обновления пользователей мне немного затруднительно применить данный подход. 
Возможно стоит делать не HashMap<Long, User>, а Set<User>. Но насколько это будет эффективнее мне оценить сложно))

2023-10-25 12:45 UTC, TY95MC commented on src/main/java/ru/practicum/shareit/item/model/ItemMapper.java
> +public class ItemMapper {
Попробовал применить информацию из статьи. Класс реализации, описанный в пункте 4.3 данной статьи, оказался не таким, как в примере(не появилось строк с сеттерами; при попытке прописать вручную IDE запретила мне его модифицировать). Вдобавок выскочила куча ошибок cannot find symbol во всех местах, где я использую .builder(),build() и еще в классе ErrorHandler и в других местах. В этом проекте на данном этапе я пока оставлю свою реализацию, но спасибо за статью! Хотя и не все понял из нее) Но полагал, что, выполняя шаги как в статье, все будет ок

2023-10-25 14:53 UTC, AnastasiyaFomkina approved these changes

2023-11-16 15:38 UTC, merged