Add bookings
TY95MC/java-shareit pull request #2
Opened 2023-11-16 15:36 UTC by TY95MC

2023-11-16 21:40 UTC, AnastasiyaFomkina requested changes

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        checkIfItemNotBelongsToBooker(dto.getItemId(), userId);
В строке 43 мы уже получили вещь из базы, еще раз ходить и доставать ее от туда, чтобы принадлежит ли она этому пользователю - лишняя нагрузка на сервис

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                .booker(userRepository.getReferenceById(userId))
Нужно использовать `findById` и сразу выбрасывать ошибку, если `Optional` пуст

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking booking = Booking.builder()
Нужно создать метод в маппере, который будет преобразовывать `InputBookingDto` в `Booking`, и использовать его здесь

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking);
в маппере должен остаться только один метод, который маппит `Booking` в `BookingDto`

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking booking = bookingRepository.getReferenceById(bookingId);
Нужно использовать `findById` и сразу выбрасывать ошибку, если `Optional` пуст

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals("APPROVED")) {
Нужно будет сравнивать с enum, а не со строкой

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        checkIfItemNotBelongsToBooker(booking.getItem().getId(), booking.getBooker().getId());
Нужно только один раз сходить в базу, достать `Item` и проверить, доступна ли вещь к бронированию и принадлежит ли она другому пользователю

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                booking.setStatus("APPROVED");
Должен быть enum, а не строка

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                booking.setStatus("REJECTED");
Должен быть enum, а не строка

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking);
Должен остаться один метод, который будет маппить `Booking` в `BookingDto`

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        checkIfUserOrItemOrBookingExists(userId, null, bookingId);
Нужно достать только нужные объекты из базы с помощью `findById` и сразу выбрасывать ошибку, если `Optional` пуст

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        checkIfUserOrItemOrBookingExists(userId, null, bookingId);
Нужно достать только нужные объекты из базы с помощью `findById` и сразу выбрасывать ошибку, если `Optional` пуст

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Booking booking = bookingRepository.getReferenceById(bookingId);
Нужно использовать `findById` и сразу выбрасывать ошибку, если `Optional` пуст

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            return mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking);
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (state) {
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Нужно создать enum `BookingState` и использовать его, а не строки

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        checkIfUserOrItemOrBookingExists(userId, null, null);
Нужно достать только нужные объекты из базы с помощью `findById` и сразу выбрасывать ошибку, если `Optional` пуст

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        checkIfUserOrItemOrBookingExists(userId, null, null);
Нужно использовать `findById` и сразу выбрасывать ошибку, если `Optional` пуст

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            case "ALL":
Здесь должен быть enum

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        switch (state) {
Тут тоже лучше будет использовать цепочку обязанностей

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                        .map(booking -> mapToBookingDtoFull(BookingMapper.mapToBookingDto(booking), booking))
Должен остаться один метод в маппере

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return tmp.map(BookingMapper::mapToBookingDtos).orElse(null);
Мы точно хотим возвращать null, если не нашли нужные бронирования?

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return tmp.map(BookingMapper::mapToBookingInfoDto).orElse(null);
Мы точно хотим возвращать null, если не нашли нужные бронирования?

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    Long id;
Не хватает модификаторов доступа у полей класса

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/model/ItemMapper.java
> +public class ItemMapper {
Должен остаться только один маппер

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +@Service
Лишняя аннотация

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            Item item = ItemMapper.mapToItem(dto, userRepository.getReferenceById(userId));
Все использования `getReferenceById` нужно заменить на `findById`

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private void checkIfUserOrItemExists(Long userId, Long itemId) {
Нужно избавиться от данного метода по примеру из класса `BookingService`

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                .map(ItemMapper::mapToItemDto)
Должен остаться только один метод, который маппит `Item` в `ItemDto`

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        comment.setAuthor(userRepository.getReferenceById(userId));
Нужно только один раз получить нужную сущность из базы и переиспользовать ее, а не ходить каждый раз в базу, когда она нам нужна. Поэтому важно избавиться от метода `checkIfUserOrItemExists`

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +@Service
Лишняя

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = repository.getReferenceById(dto.getId());
Нужно заменить на `findById`, ходить в базу нужно только один раз

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        checkIfExistsById(id);
Нужно избавиться от этой проверки

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/resources/schema.sql
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2023-11-16 21:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/dto/InputBookingDto.java
> +    private LocalDateTime end;
Лучше добавить [@JsonFormat](https://www.baeldung.com/spring-boot-formatting-json-dates) для полей с датой, так мы можем избежать множественных ошибок при парсинге даты из json

2023-11-17 14:45 UTC, TY95MC commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        dto.setStatus("WAITING");
При создании нового букинга, его статус должен быть WAITING

2023-11-18 17:09 UTC, TY95MC commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return tmp.map(BookingMapper::mapToBookingDtos).orElse(null);
Для тестов постмана нужно, чтобы значения некстБукинга и ластБукинга были null, если мы их не нашли в базе. Если не нашлось ничего, то можно просто пробросить null, а уже при сборке itemDto можно ничего не делать, если букинг пришел null, поскольку он не инициализирован и так, но программа при этом не упадет с NPE
По крайней мере, я не придумал ничего лучше)

2023-11-19 12:56 UTC, TY95MC commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Item item = itemRepository.getReferenceById(dto.getItemId());
Что-то у меня по этой ссылке идет выход на испанский сайт с туристическими рекомендациями на праздничные выходные в 23 году :)

2023-11-19 14:31 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        dto.setStatus("WAITING");
Так как InputBookingDto используется только для создания, то нужно сразу ему в конструкторе установить этот статус

2023-11-19 14:32 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        Item item = itemRepository.getReferenceById(dto.getItemId());
https://habr.com/ru/articles/346782/

2023-11-21 21:43 UTC, AnastasiyaFomkina approved these changes

2023-12-01 21:43 UTC, merged